/**
 * FME ACP Styles Tab
 * Allows the user to write, upload and apply custom CSS to the Forumotion Admin Panel.
 * CSS is persisted in chrome.storage.local and re-applied automatically on every ACP page load.
 *
 * Features:
 *   - Code editor with live preview
 *   - Upload .css files (appended to current CSS)
 *   - Built-in "Dark 2026" preset theme
 *   - Auto-apply on every ACP page load
 */

var FMEAcpCssTab = (() => {
  'use strict';

  const STORAGE_KEY      = 'fme_acp_custom_css';
  const ACTIVE_THEME_KEY = 'fme_acp_active_theme';
  const STYLE_TAG_ID     = 'fme-acp-custom-style';

  /* ─── Built-in preset: Dark 2026 ─────────────────────────────────────────── */
  const PRESET_2026 = `/* =================================================
   FME Dark 2026 — ACP Theme
   Modern deep-space aesthetic for Forumotion ACP
   Generated by FME Extension
   ================================================= */

:root {
  --fme-bg:      #0f1117;
  --fme-surface: #171923;
  --fme-card:    #1a1f2e;
  --fme-border:  #252d3d;
  --fme-accent:  #6c63ff;
  --fme-cyan:    #00d2ff;
  --fme-text:    #e2e8f0;
  --fme-muted:   #64748b;
  --fme-success: #10b981;
  --fme-error:   #f43f5e;
  --fme-warn:    #f59e0b;
  --fme-radius:  8px;
  --fme-shadow:  0 4px 24px rgba(0,0,0,0.45);
}

/* === GLOBAL === */
body {
  background: var(--fme-bg) !important;
  color: var(--fme-text) !important;
  font-family: 'Segoe UI', system-ui, -apple-system, sans-serif !important;
}

/* === HEADER === */
#page-header {
  background: linear-gradient(135deg, #0f1117 0%, #171923 100%) !important;
  border-bottom: 1px solid var(--fme-border) !important;
  box-shadow: 0 2px 16px rgba(0,0,0,0.4) !important;
}
.logo-header { background: transparent !important; }
#page-header a, #page-header p, #page-header a:hover {
  color: var(--fme-text) !important;
}
.right-header {
  border-left-color: var(--fme-border) !important;
  transition: background 0.2s !important;
}
.right-header:hover {
  background: rgba(108,99,255,0.1) !important;
  border-left-color: var(--fme-accent) !important;
}
.right-menu-header {
  background: var(--fme-card) !important;
  border: 1px solid var(--fme-border) !important;
  box-shadow: var(--fme-shadow) !important;
}
.right-menu-header::after { border-bottom-color: var(--fme-card) !important; }
.right-menu-header span.dark_mode_toggle,
.right-menu-header a { color: var(--fme-text) !important; }
.right-menu-header a:hover {
  background: rgba(108,99,255,0.1) !important;
  color: var(--fme-accent) !important;
}
.avatar-header > img {
  border-color: var(--fme-border) !important;
  background: var(--fme-surface) !important;
}
#page-header ul.preview_forum li {
  background: rgba(108,99,255,0.15) !important;
  border-radius: 6px !important;
}
#page-header ul.preview_forum li a { color: var(--fme-text) !important; }

/* === TOP TABS NAV === */
#tabs {
  background: var(--fme-surface) !important;
  border-bottom: 1px solid var(--fme-border) !important;
  box-shadow: 0 2px 8px rgba(0,0,0,0.2) !important;
}
#tabs a { color: var(--fme-muted) !important; }
#tabs a span {
  border-radius: 4px 4px 0 0 !important;
  transition: all 0.2s ease !important;
}
#tabs a:hover span {
  background: rgba(108,99,255,0.12) !important;
  color: var(--fme-text) !important;
}
#tabs #activetab a span {
  background: rgba(108,99,255,0.2) !important;
  color: var(--fme-accent) !important;
  box-shadow: inset 0 -2px 0 var(--fme-accent) !important;
}
#tabs #admin_search_input {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
  color: var(--fme-text) !important;
  border-radius: 6px !important;
}
#tabs #admin_search_results {
  background: var(--fme-card) !important;
  border: 1px solid var(--fme-border) !important;
  box-shadow: var(--fme-shadow) !important;
  border-radius: 0 0 var(--fme-radius) var(--fme-radius) !important;
}
#tabs #admin_search_results li a {
  background: var(--fme-surface) !important;
  border-color: var(--fme-border) !important;
  color: var(--fme-accent) !important;
  border-radius: 6px !important;
}

/* === CONTENT AREA (keep float layout intact!) === */
#content {
  background: var(--fme-bg) !important;
  color: var(--fme-text) !important;
}

/* === SIDEBAR MENU === */
#menu {
  background: var(--fme-surface) !important;
  border-right: 1px solid var(--fme-border) !important;
  border-bottom: 1px solid var(--fme-border) !important;
}
#menu .header {
  color: var(--fme-accent) !important;
  font-size: 0.72em !important;
  font-weight: 700 !important;
  letter-spacing: 0.1em !important;
}
.left-top { color: var(--fme-text) !important; }
#menu .submenu {
  border-bottom: 1px solid var(--fme-border) !important;
  transition: background 0.15s !important;
  height: auto !important;
  line-height: 2.1 !important;
}
#menu .submenu a span {
  color: var(--fme-muted) !important;
  transition: color 0.15s !important;
}
#menu .submenu a:hover,
#menu .submenu a:hover span {
  background: rgba(108,99,255,0.1) !important;
  color: var(--fme-text) !important;
}
#menu #activesubmenu {
  border-bottom-color: var(--fme-border) !important;
  background: rgba(108,99,255,0.1) !important;
  border-left: 3px solid var(--fme-accent) !important;
  box-shadow: inset 4px 0 12px rgba(108,99,255,0.12) !important;
}
#menu #activesubmenu a {
  background: transparent !important;
  color: var(--fme-accent) !important;
}
#menu #activesubmenu a:hover {
  background: rgba(108,99,255,0.15) !important;
  color: var(--fme-accent) !important;
}
#menu #admin_version {
  background: var(--fme-card) !important;
  border-radius: var(--fme-radius) !important;
  margin: 8px !important;
  border: 1px solid var(--fme-border) !important;
}

/* === MAIN AREA === */
#main, #main-content { background: var(--fme-bg) !important; }
#tools { color: var(--fme-muted) !important; }
#tools fieldset { background: var(--fme-card) !important; }

/* Headings */
h1 { color: var(--fme-text) !important; }
h2, .likeh2 { color: var(--fme-accent) !important; }
h2 a { color: var(--fme-accent) !important; }
h2 a:hover {
  color: var(--fme-cyan) !important;
  border-bottom-color: var(--fme-cyan) !important;
}
caption { color: var(--fme-accent) !important; }
legend { color: var(--fme-accent) !important; }

/* Breadcrumb */
ul.h2-breadcrumb { color: var(--fme-muted) !important; }
ul.h2-breadcrumb li a { color: var(--fme-accent) !important; }
ul.h2-breadcrumb li a:hover { color: var(--fme-cyan) !important; }

/* Links */
a:link, a:active, a:visited { color: var(--fme-accent) !important; }
a:hover { color: var(--fme-cyan) !important; }
p { color: var(--fme-text) !important; }
hr { border-top-color: var(--fme-border) !important; }

/* === TABLES === */
table.grey {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
}
th {
  background: linear-gradient(135deg, #4c46b8, var(--fme-accent)) !important;
  color: #fff !important;
}
th.nobg {
  background: var(--fme-card) !important;
  color: var(--fme-muted) !important;
}
td { color: var(--fme-text) !important; }
.row1 { background: var(--fme-card) !important; }
.row2 { background: transparent !important; }
.row3 { background: var(--fme-surface) !important; }
.row4 { background: #1c2035 !important; }
.col1 { background: #1c2035 !important; }
.col2 { background: var(--fme-card) !important; }
.admin_rows_alternate tr:nth-child(even) { background: var(--fme-card) !important; }
.admin_rows_alternate tr:nth-child(odd)  { background: transparent !important; }

/* === PANELS === */
.panel {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
  border-radius: var(--fme-radius) !important;
}
.panel_menu, .panel_menu_simple {
  background: var(--fme-surface) !important;
  border-color: var(--fme-border) !important;
}

/* === FORMS === */
fieldset {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
  color: var(--fme-muted) !important;
  border-radius: var(--fme-radius) !important;
  box-shadow: none !important;
}
fieldset p { color: var(--fme-text) !important; }
table.like-fieldset {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
}
input:not([type="button"]):not([type="submit"]):not([type="radio"]):not([type="checkbox"]):not([type="file"]),
select,
textarea {
  background: var(--fme-surface) !important;
  border-color: var(--fme-border) !important;
  color: var(--fme-text) !important;
  border-radius: 6px !important;
}
input:focus, textarea:focus, select:focus {
  border-color: var(--fme-accent) !important;
  box-shadow: 0 0 0 3px rgba(108,99,255,0.2) !important;
  outline: none !important;
}
input[disabled], button[disabled], textarea[disabled] {
  background: rgba(255,255,255,0.04) !important;
  color: var(--fme-muted) !important;
}
label { color: var(--fme-text) !important; }
dt { color: var(--fme-muted) !important; }
dd { color: var(--fme-text) !important; }
.field_title, .field_title a { color: var(--fme-accent) !important; }
fieldset.warning {
  background: rgba(245,158,11,0.07) !important;
  border-color: rgba(245,158,11,0.35) !important;
}
fieldset.alert {
  background: rgba(244,63,94,0.07) !important;
  border-color: rgba(244,63,94,0.35) !important;
}
fieldset.warning_cadeau {
  background: rgba(16,185,129,0.07) !important;
  border-color: rgba(16,185,129,0.35) !important;
}

/* === GREYBOXES === */
.greyboxes {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
}
.greyboxes h2 {
  background: linear-gradient(135deg, #4c46b8, var(--fme-accent)) !important;
  color: #fff !important;
}

/* === BUTTONS === */
input[type="button"], input[type="submit"], button, .btn, .div_btns a {
  background: var(--fme-card) !important;
  border: 1px solid var(--fme-border) !important;
  color: var(--fme-text) !important;
  border-radius: 6px !important;
  transition: border-color 0.2s, background 0.2s, box-shadow 0.2s !important;
  text-transform: none !important;
  font-weight: 500 !important;
}
.btn:hover {
  background: var(--fme-surface) !important;
  border-color: var(--fme-accent) !important;
  color: var(--fme-accent) !important;
  box-shadow: 0 0 12px rgba(108,99,255,0.2) !important;
}
a.btn, a.btn:hover { color: var(--fme-text) !important; }
a.btn:hover { color: var(--fme-accent) !important; }
.icon_add, .icon_ok {
  background: linear-gradient(135deg, var(--fme-success), #059669) !important;
  border-color: transparent !important;
  color: #fff !important;
}
.icon_add:hover, .icon_ok:hover {
  box-shadow: 0 0 16px rgba(16,185,129,0.35) !important;
}
.icon_cancel {
  background: linear-gradient(135deg, var(--fme-error), #e11d48) !important;
  border-color: transparent !important;
  color: #fff !important;
}
.icon_cancel:hover {
  box-shadow: 0 0 16px rgba(244,63,94,0.35) !important;
}

/* === STATUS BOXES === */
.successbox, .warning-navbar {
  background: rgba(16,185,129,0.08) !important;
  border-color: rgba(16,185,129,0.3) !important;
  border-radius: var(--fme-radius) !important;
}
.successbox h3, .warning-navbar h3 { color: var(--fme-success) !important; }
.errorbox {
  background: rgba(244,63,94,0.08) !important;
  border-color: rgba(244,63,94,0.3) !important;
  border-radius: var(--fme-radius) !important;
}
.errorbox h3 { color: var(--fme-error) !important; }
.messagebox {
  background: rgba(245,158,11,0.08) !important;
  border-color: rgba(245,158,11,0.3) !important;
  border-radius: var(--fme-radius) !important;
}
.messagebox h3 { color: var(--fme-warn) !important; }

/* === SUB NAV TABS === */
#tabs_menu a span { color: var(--fme-muted) !important; }
#tabs_menu #activetab a span { color: var(--fme-success) !important; }
#tabs_menu a:hover span { color: var(--fme-accent) !important; }

/* === FOOTER === */
#page-footer {
  background: var(--fme-surface) !important;
  color: var(--fme-muted) !important;
  border-top: 1px solid var(--fme-border) !important;
}
#page-footer li a { color: var(--fme-muted) !important; }
#page-footer li a:hover { color: var(--fme-text) !important; }
#page-footer strong.h3, #page-footer h3 { color: var(--fme-accent) !important; }

/* === CODEMIRROR / SCEDITOR === */
div.CodeMirror {
  background: var(--fme-surface) !important;
  border-color: var(--fme-border) !important;
  color: var(--fme-text) !important;
  border-radius: var(--fme-radius) !important;
}
.sceditor-container { border-color: var(--fme-border) !important; }
div.sceditor-toolbar { border-bottom-color: var(--fme-border) !important; }

/* === NOTEPAD === */
.notepad-content #notepad {
  background: var(--fme-surface) !important;
  color: var(--fme-text) !important;
  border-color: var(--fme-border) !important;
}

/* === MAIN ICON GRID === */
.main_icones_link:hover,
.main_icones a:hover {
  background: rgba(108,99,255,0.1) !important;
  border-radius: var(--fme-radius) !important;
}
a.main_icones_link span::before,
.main_icones a strong::before { color: var(--fme-accent) !important; }

/* === PAGINATION === */
.pagination span strong {
  background: var(--fme-accent) !important;
  border-color: var(--fme-accent) !important;
  color: #fff !important;
}
.pagination span a {
  color: var(--fme-muted) !important;
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
}
.pagination span a:hover {
  background: var(--fme-accent) !important;
  border-color: var(--fme-accent) !important;
  color: #fff !important;
}

/* === MISC === */
.success { color: var(--fme-success) !important; }
.error   { color: var(--fme-error)   !important; }
.message { color: var(--fme-warn)    !important; }
.txt_blue, .txt_blue:hover { color: var(--fme-accent) !important; }
a.txt_green { color: var(--fme-success) !important; }
.red-color   { color: var(--fme-error)   !important; }
.green-color { color: var(--fme-success) !important; }
div.avatar {
  background: var(--fme-card) !important;
  border-color: var(--fme-border) !important;
}

/* === DRAG & DROP (forum structure) === */
.gu-mirror.cat, .gu-mirror .cat,
#sortable .cat > .sort_el.highlight,
#sortable .cat {
  background-color: rgba(108,99,255,0.15) !important;
  border-color: var(--fme-accent) !important;
}

/* === AWARD TOOLTIPS === */
.award_tooltiptext {
  background: var(--fme-card) !important;
  border-color: var(--fme-accent) !important;
  color: var(--fme-accent) !important;
}

/* === SCROLLBAR === */
::-webkit-scrollbar { width: 6px; height: 6px; }
::-webkit-scrollbar-track { background: var(--fme-bg); }
::-webkit-scrollbar-thumb { background: var(--fme-border); border-radius: 4px; }
::-webkit-scrollbar-thumb:hover { background: var(--fme-accent); }

/* === SELECTION === */
::selection { background: rgba(108,99,255,0.35); color: #fff; }`;

  let _container  = null;
  let _currentCss  = '';
  let _guardActive = false;

  // ─── Theme catalog ────────────────────────────────────────────────────────────

  function _getBaseRules() {
    const marker = '\n/* === GLOBAL === */';
    const idx = PRESET_2026.indexOf(marker);
    return idx >= 0 ? PRESET_2026.slice(idx) : '';
  }

  function buildThemeCss(vars, name) {
    return '/* FME Theme: ' + name + ' */\n:root {\n' +
      '  --fme-bg:      ' + vars.bg      + ';\n' +
      '  --fme-surface: ' + vars.surface + ';\n' +
      '  --fme-card:    ' + vars.card    + ';\n' +
      '  --fme-border:  ' + vars.border  + ';\n' +
      '  --fme-accent:  ' + vars.accent  + ';\n' +
      '  --fme-cyan:    ' + vars.cyan    + ';\n' +
      '  --fme-text:    ' + vars.text    + ';\n' +
      '  --fme-muted:   ' + vars.muted   + ';\n' +
      '  --fme-success: ' + vars.success + ';\n' +
      '  --fme-error:   ' + vars.error   + ';\n' +
      '  --fme-warn:    ' + vars.warn    + ';\n' +
      '  --fme-radius:  ' + (vars.radius || '8px') + ';\n' +
      '  --fme-shadow:  ' + (vars.shadow || '0 4px 24px rgba(0,0,0,0.45)') + ';\n' +
      '}\n' + _getBaseRules();
  }

  const PRESET_THEMES = [
    {
      id: 'dark-2026', name: 'Dark 2026',
      description: 'Spațiu profund & violet electric',
      swatches: ['#0f1117', '#6c63ff', '#00d2ff', '#10b981'],
      get css() { return PRESET_2026; },
    },
    {
      id: 'nord', name: 'Nord',
      description: 'Polare arctice & albastru nordic',
      swatches: ['#2e3440', '#88c0d0', '#a3be8c', '#bf616a'],
      vars: { bg: '#2e3440', surface: '#3b4252', card: '#434c5e', border: '#4c566a',
               accent: '#88c0d0', cyan: '#81a1c1', text: '#eceff4', muted: '#d8dee9',
               success: '#a3be8c', error: '#bf616a', warn: '#ebcb8b' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'dracula', name: 'Dracula',
      description: 'Violet & roz vampiric clasic',
      swatches: ['#282a36', '#bd93f9', '#50fa7b', '#ff5555'],
      vars: { bg: '#282a36', surface: '#21222c', card: '#2d2f40', border: '#44475a',
               accent: '#bd93f9', cyan: '#ff79c6', text: '#f8f8f2', muted: '#6272a4',
               success: '#50fa7b', error: '#ff5555', warn: '#ffb86c', radius: '6px' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'solarized', name: 'Solarized Dark',
      description: 'Tonuri calde oceanice Solarized',
      swatches: ['#002b36', '#268bd2', '#859900', '#dc322f'],
      vars: { bg: '#002b36', surface: '#073642', card: '#0c3d48', border: '#586e75',
               accent: '#268bd2', cyan: '#2aa198', text: '#839496', muted: '#657b83',
               success: '#859900', error: '#dc322f', warn: '#b58900', radius: '4px',
               shadow: '0 4px 24px rgba(0,0,0,0.5)' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'forest', name: 'Forest Night',
      description: 'Dark & verde ca GitHub Night',
      swatches: ['#0d1117', '#3fb950', '#58a6ff', '#f85149'],
      vars: { bg: '#0d1117', surface: '#161b22', card: '#1c2128', border: '#30363d',
               accent: '#3fb950', cyan: '#58a6ff', text: '#c9d1d9', muted: '#8b949e',
               success: '#3fb950', error: '#f85149', warn: '#d29922', radius: '6px' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'midnight', name: 'Midnight Blue',
      description: 'Albastru nocturn profund & corporate',
      swatches: ['#060e1d', '#4078c0', '#34d399', '#f87171'],
      vars: { bg: '#060e1d', surface: '#0a1628', card: '#0d1f35', border: '#1a3050',
               accent: '#4078c0', cyan: '#79b8ff', text: '#d1d5db', muted: '#6b7280',
               success: '#34d399', error: '#f87171', warn: '#fbbf24',
               shadow: '0 4px 24px rgba(0,0,0,0.6)' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'coffee', name: 'Coffee',
      description: 'Tonuri calde de cafea & chihlimbar',
      swatches: ['#1c1410', '#c87941', '#84c754', '#e9553c'],
      vars: { bg: '#1c1410', surface: '#24201a', card: '#2d2720', border: '#3d3530',
               accent: '#c87941', cyan: '#e8a97a', text: '#e8d5b7', muted: '#a08060',
               success: '#84c754', error: '#e9553c', warn: '#f59e0b', radius: '6px' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
    {
      id: 'catppuccin', name: 'Catppuccin Mocha',
      description: 'Pasteluri moi & elegant modern',
      swatches: ['#1e1e2e', '#cba6f7', '#a6e3a1', '#f38ba8'],
      vars: { bg: '#1e1e2e', surface: '#181825', card: '#1e1e2e', border: '#313244',
               accent: '#cba6f7', cyan: '#89dceb', text: '#cdd6f4', muted: '#a6adc8',
               success: '#a6e3a1', error: '#f38ba8', warn: '#f9e2af', radius: '8px' },
      get css() { return buildThemeCss(this.vars, this.name); },
    },
  ];

  // ─── Public API ──────────────────────────────────────────────────────────────

  function render(container) {
    _container = container;
    container.innerHTML = '';

    const wrapper = document.createElement('div');
    wrapper.className = 'fme-acpcss-wrapper main-content';
    wrapper.id = 'main-content';
    wrapper.style.fontSize = '12px';

    wrapper.innerHTML = `
      <div class="fme-section-header">
        <h2 class="fme-section-title">FME</h2>
        <ul class="h2-breadcrumb clearfix"><li class="first">ACP Styles</li></ul>
        <blockquote class="block_left">
          <p class="explain">Aplică o temă predefinită sau scrie CSS-ul tău personalizat pentru Panoul de Administrare. Modificările se aplică live și se salvează automat.</p>
        </blockquote>
      </div>

      <div id="fme-theme-catalog-area"></div>

      <fieldset class="fieldset_left">
        <legend>CSS personalizat ACP</legend>
        <dl>
            <textarea id="fme-acp-css-editor"
            style="height:380px;font-family:Consolas,'Cascadia Code','Fira Code',monospace;font-size:12px;line-height:1.6;padding:12px;border:1px solid var(--fme-border,#cdcdcd);border-radius:6px;resize:vertical;background:var(--fme-surface,#efefef);color:var(--fme-text,#2a2a2a);tab-size:2;box-sizing:border-box;"
            placeholder="/* Scrie CSS personalizat sau foloseste butonul de mai sus */&#10;#page-header { background: #cecece !important; }"></textarea>
        </dl>

        <div class="div_btns" style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;justify-content:flex-start;margin-bottom:10px;">
          <input type="button" id="fme-css-save"   value="Salveaza &amp; Aplica"  class="icon_ok" />
          <input type="button" id="fme-css-upload" value="Incarca fisier .css"    class="btn" />
          <input type="button" id="fme-css-clear"  value="Sterge tot"             class="icon_cancel" />
          <input type="file"   id="fme-css-file-input" accept=".css,text/css" style="display:none;" />
        </div>
        <div style="display:flex;align-items:center;gap:12px;margin-top:6px;flex-wrap:wrap;">
          <span id="fme-css-status" style="font-size:11px;font-weight:600;min-width:130px;"></span>
          <span id="fme-css-info"   style="font-size:11px;font-family:Consolas,monospace;color:var(--fme-muted,#64748b);"></span>
        </div>
      </fieldset>
    `;

    container.appendChild(wrapper);
    buildCatalogSection(wrapper);
    bindEvents(wrapper);
    loadSaved(wrapper);
  }

  // ─── Load saved CSS ───────────────────────────────────────────────────────────

  function loadSaved(wrapper) {
    chrome.storage.local.get({ [STORAGE_KEY]: '', [ACTIVE_THEME_KEY]: '' }, (result) => {
      const css = result[STORAGE_KEY] || '';
      wrapper.querySelector('#fme-acp-css-editor').value = css;
      updateInfo(wrapper, css);
      highlightActiveTheme(wrapper, result[ACTIVE_THEME_KEY] || '');
    });
  }

  // ─── Events ───────────────────────────────────────────────────────────────────

  function bindEvents(wrapper) {
    const editor    = wrapper.querySelector('#fme-acp-css-editor');
    const saveBtn   = wrapper.querySelector('#fme-css-save');
    const uploadBtn = wrapper.querySelector('#fme-css-upload');
    const clearBtn  = wrapper.querySelector('#fme-css-clear');
    const fileInput = wrapper.querySelector('#fme-css-file-input');
    const statusEl  = wrapper.querySelector('#fme-css-status');

    // Live preview + clear active theme when user edits manually
    editor.addEventListener('input', () => {
      applyToPage(editor.value);
      chrome.storage.local.set({ [ACTIVE_THEME_KEY]: '' });
      highlightActiveTheme(wrapper, '');
    });

    // Tab key → 2 spaces
    editor.addEventListener('keydown', (e) => {
      if (e.key === 'Tab') {
        e.preventDefault();
        const s = editor.selectionStart, en = editor.selectionEnd;
        editor.value = editor.value.substring(0, s) + '  ' + editor.value.substring(en);
        editor.selectionStart = editor.selectionEnd = s + 2;
      }
    });

    // Save
    saveBtn.addEventListener('click', () => {
      const css = editor.value.trim();
      chrome.storage.local.set({ [STORAGE_KEY]: css }, () => {
        applyToPage(css);
        updateInfo(wrapper, css);
        setStatus(statusEl, 'Salvat si aplicat!', '#10b981');
        if (typeof FMEActivityLog !== 'undefined') FMEActivityLog.log('css-acp-save', 'CSS ACP salvat (' + css.split('\n').length + ' linii)');
      });
    });

    // Upload .css file
    uploadBtn.addEventListener('click', () => fileInput.click());
    fileInput.addEventListener('change', () => {
      const file = fileInput.files[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (ev) => {
        const existing  = editor.value.trim();
        const separator = existing
          ? `\n\n/* \u2500\u2500\u2500 ${file.name} \u2500\u2500\u2500 */\n`
          : `/* ${file.name} */\n`;
        editor.value = existing ? existing + separator + ev.target.result : ev.target.result;
        applyToPage(editor.value);
        updateInfo(wrapper, editor.value);
        setStatus(statusEl, `${file.name} incarcat!`, '#6c63ff');
      };
      reader.readAsText(file);
      fileInput.value = '';
    });

    // Clear
    clearBtn.addEventListener('click', () => {
      if (!editor.value.trim()) return;
      if (!confirm('Stergi tot CSS-ul custom din ACP?')) return;
      editor.value = '';
      chrome.storage.local.set({ [STORAGE_KEY]: '', [ACTIVE_THEME_KEY]: '' }, () => {
        applyToPage('');
        updateInfo(wrapper, '');
        highlightActiveTheme(wrapper, '');
        setStatus(statusEl, 'Sters.', '#f43f5e');
      });
    });
  }

  // ─── Apply CSS to the page ────────────────────────────────────────────────────

  function applyToPage(css) {
    _currentCss = css;
    let tag = document.getElementById(STYLE_TAG_ID);
    if (!tag) {
      tag = document.createElement('style');
      tag.id = STYLE_TAG_ID;
    }
    tag.textContent = css;
    // Always append last so we win over any ACP stylesheet in the cascade
    document.head.appendChild(tag);
  }

  // ─── Persistent style guard ───────────────────────────────────────────────
  // Watches document.head: re-injects our tag if removed, keeps it last if
  // the ACP adds new stylesheets after ours (AJAX, dynamic link injection, etc.)

  function startStyleGuard() {
    if (_guardActive) return;
    _guardActive = true;

    const obs = new MutationObserver(() => {
      if (!_currentCss) return;
      const tag = document.getElementById(STYLE_TAG_ID);
      if (!tag || !document.head.contains(tag)) {
        // Tag was removed entirely — re-inject
        applyToPage(_currentCss);
      } else if (tag !== document.head.lastElementChild) {
        // ACP added something after us — move our tag to end (highest priority)
        document.head.appendChild(tag);
      }
    });

    obs.observe(document.head, { childList: true });
  }

  // ─── Update info box ──────────────────────────────────────────────────────────

  function updateInfo(wrapper, css) {
    const info = wrapper.querySelector('#fme-css-info');
    if (!info) return;
    if (!css.trim()) {
      info.textContent = 'Niciun CSS salvat.';
      return;
    }
    const lines = css.split('\n').length;
    const kb    = (new Blob([css]).size / 1024).toFixed(1);
    info.textContent = `${lines} linii \u00b7 ${kb} KB \u00b7 aplicat automat`;
  }

  // ─── Status helper ────────────────────────────────────────────────────────────

  function setStatus(el, msg, color) {
    el.style.color = color || '#10b981';
    el.textContent = msg;
    setTimeout(() => { el.textContent = ''; }, 3000);
  }

  function escHtml(str) {
    return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  // ─── Theme catalog UI ────────────────────────────────────────────────────────

  function buildCatalogSection(wrapper) {
    const area = wrapper.querySelector('#fme-theme-catalog-area');
    if (!area) return;

    const section = document.createElement('div');
    section.className = 'panel-menu';
    //section.style.cssText = 'margin:0 0 10px 0!important;background:#fff!important;border:1px solid #cdcdcd!important;padding:0 0 10px 0!important;';
    section.innerHTML = `
      <br/><fieldset style="margin:0 12px 12px 12px;border-color:var(--fme-accent,#4a7ebf);">
        <legend style="color:var(--fme-accent,#4a7ebf);font-weight:600;">&#127912; Teme ACP predefinite</legend>
        <p style="margin:4px 0 12px 0;color:var(--fme-muted,#666);font-size:11px;">
          Selectează o temă ready-to-use pentru panoul de administrare. CSS-ul este aplicat live și salvat automat.<br/>
          Poți edita CSS-ul manual mai jos pentru personalizări suplimentare.
        </p>
        <div id="fme-theme-cards" style="display:flex;flex-wrap:wrap;gap:10px;"></div>
      </fieldset>
    `;

    const cardsContainer = section.querySelector('#fme-theme-cards');
    PRESET_THEMES.forEach(theme => {
      const card = document.createElement('div');
      card.className = 'fme-theme-card';
      card.dataset.themeId = theme.id;
      card.style.cssText = 'width:140px;padding:10px;border:2px solid var(--fme-border,#ddd);border-radius:6px;background:var(--fme-card,#f9f9f9);cursor:default;transition:border-color 0.2s,box-shadow 0.2s,background 0.2s;';

      const swatches = (theme.swatches || ['#333', '#555', '#777', '#999'])
        .map(c => `<span style="flex:1;height:18px;background:${escHtml(c)};border-radius:3px;"></span>`)
        .join('');

      card.innerHTML = `
        <div style="display:flex;gap:2px;margin-bottom:8px;">${swatches}</div>
        <div style="font-weight:600;font-size:12px;color:var(--fme-text,#333);margin-bottom:4px;">${escHtml(theme.name)}</div>
        <div style="font-size:10px;color:var(--fme-muted,#666);margin-bottom:8px;line-height:1.4;">${escHtml(theme.description)}</div>
        <input type="button" class="fme-apply-theme-btn icon_ok" data-theme-id="${escHtml(theme.id)}"
               value="Activează" style="width:100%;font-size:11px;padding:3px 0;" />
      `;

      card.querySelector('.fme-apply-theme-btn').addEventListener('click', () => {
        applyTheme(theme, wrapper);
      });

      cardsContainer.appendChild(card);
    });

    area.appendChild(section);
  }

  function applyTheme(theme, wrapper) {
    const css      = theme.css;
    const editor   = wrapper.querySelector('#fme-acp-css-editor');
    const statusEl = wrapper.querySelector('#fme-css-status');

    if (editor) editor.value = css;
    applyToPage(css);
    updateInfo(wrapper, css);

    chrome.storage.local.set({ [STORAGE_KEY]: css, [ACTIVE_THEME_KEY]: theme.id }, () => {
      setStatus(statusEl, theme.name + ' activat!', '#4a7ebf');
      highlightActiveTheme(wrapper, theme.id);
      if (typeof FMEActivityLog !== 'undefined') FMEActivityLog.log('css-acp-save', 'Temă ACP aplicată: ' + theme.name);
    });
  }

  function highlightActiveTheme(wrapper, activeId) {
    const accent  = 'var(--fme-accent, #4a7ebf)';
    const cardBg  = 'var(--fme-card, #f9f9f9)';
    const border  = 'var(--fme-border, #ddd)';

    wrapper.querySelectorAll('.fme-theme-card').forEach(card => {
      const id  = card.dataset.themeId;
      const btn = card.querySelector('.fme-apply-theme-btn');
      if (id === activeId) {
        card.style.borderColor = accent;
        card.style.background  = cardBg;
        card.style.boxShadow   = '0 0 0 2px rgba(74,126,191,0.4)';
        if (btn) { btn.value = '\u2713 Activ'; btn.disabled = true; }
      } else {
        card.style.borderColor = border;
        card.style.background  = cardBg;
        card.style.boxShadow   = '';
        if (btn) { btn.value = 'Activează'; btn.disabled = false; }
      }
    });
  }

  // ─── Auto-apply on load / navigation (called from content.js) ──────────────

  function autoApply() {
    chrome.storage.local.get({ [STORAGE_KEY]: '' }, (result) => {
      const css = result[STORAGE_KEY] || '';
      if (css) applyToPage(css);
      startStyleGuard();
    });
  }

  return { render, autoApply };
})();
